services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:ollama
    volumes:
      - open-webui:/app/backend/data
      - ollama:/root/.ollama
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      open-webui:
        condition: service_healthy

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      caddy:
        condition: service_healthy

volumes:
  open-webui:
  ollama:
  caddy_data:
  caddy_config: